"""
HTML report generation using Jinja2 templates with embedded Plotly charts.
"""

import logging
from pathlib import Path

import pandas as pd
from jinja2 import Template

from .visualization import (
    depth_growth_histogram,
    worst_n_chart,
    growth_scatter,
    segment_alignment_plot,
    remaining_life_histogram,
)

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Jinja2 HTML template
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ILI Growth Analysis Report — {{ run_a }} vs {{ run_b }}</title>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
<style>
  :root { --bg: #f8f9fa; --card: #fff; --border: #dee2e6; --text: #212529; --accent: #0d6efd; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         background: var(--bg); color: var(--text); line-height: 1.6; padding: 2rem; }
  .container { max-width: 1200px; margin: 0 auto; }
  h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
  h2 { font-size: 1.3rem; margin: 2rem 0 0.75rem; border-bottom: 2px solid var(--accent); padding-bottom: 0.3rem; }
  .meta { color: #6c757d; margin-bottom: 2rem; }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 8px;
          padding: 1.25rem; margin-bottom: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.04); }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; }
  .stat { text-align: center; }
  .stat .value { font-size: 2rem; font-weight: 700; color: var(--accent); }
  .stat .label { font-size: 0.85rem; color: #6c757d; }
  table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid var(--border); }
  th { background: var(--bg); font-weight: 600; }
  tr:hover { background: #f1f3f5; }
  .chart-container { margin: 1rem 0; }
  .footer { text-align: center; color: #adb5bd; font-size: 0.8rem; margin-top: 3rem; }
</style>
</head>
<body>
<div class="container">

<h1>ILI Growth Analysis Report</h1>
<p class="meta">{{ run_a }} vs {{ run_b }} &mdash; {{ years_between }} year gap</p>

<!-- Summary cards -->
<h2>Summary</h2>
<div class="grid">
  <div class="card stat"><div class="value">{{ n_matched }}</div><div class="label">Matched</div></div>
  <div class="card stat"><div class="value">{{ n_uncertain }}</div><div class="label">Uncertain</div></div>
  <div class="card stat"><div class="value">{{ n_missing }}</div><div class="label">Missing (Run A)</div></div>
  <div class="card stat"><div class="value">{{ n_new }}</div><div class="label">New (Run B)</div></div>
  <div class="card stat"><div class="value">{{ mean_growth }}</div><div class="label">Mean Growth (%/yr)</div></div>
  <div class="card stat"><div class="value">{{ max_growth }}</div><div class="label">Max Growth (%/yr)</div></div>
</div>

<!-- Charts -->
<h2>Growth Rate Distribution</h2>
<div class="card chart-container">{{ chart_histogram }}</div>

<h2>Depth: Run A vs Run B</h2>
<div class="card chart-container">{{ chart_scatter }}</div>

<h2>Remaining Life Distribution</h2>
<div class="card chart-container">{{ chart_remaining_life }}</div>

<h2>Worst Anomalies</h2>
<div class="card chart-container">{{ chart_worst }}</div>

{% if chart_alignment %}
<h2>Alignment Quality</h2>
<div class="card chart-container">{{ chart_alignment }}</div>
{% endif %}

<!-- Growth by feature type -->
{% if summary_table %}
<h2>Growth by Feature Type</h2>
<div class="card">
{{ summary_table }}
</div>
{% endif %}

<!-- Dig list -->
{% if dig_list_table %}
<h2>Dig List — Top 50</h2>
<div class="card">
{{ dig_list_table }}
</div>
{% endif %}

<div class="footer">Generated by pipe-align-predict</div>
</div>
</body>
</html>
""")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_html_report(
    growth_df: pd.DataFrame,
    missing_df: pd.DataFrame,
    new_df: pd.DataFrame,
    summary_df: pd.DataFrame,
    segments: list[dict],
    residuals: pd.DataFrame,
    run_id_a: str,
    run_id_b: str,
    years_between: float,
    output_path: Path,
) -> Path:
    """Generate a self-contained HTML report with interactive Plotly charts.

    Args:
        growth_df: matched anomalies with growth data.
        missing_df: Run A only anomalies.
        new_df: Run B only anomalies.
        summary_df: growth summary by feature type.
        segments: alignment segment dicts.
        residuals: alignment residuals DataFrame.
        run_id_a, run_id_b: run identifiers.
        years_between: gap in years.
        output_path: where to write the HTML file.

    Returns:
        Path to the generated HTML file.
    """
    # Compute stats
    n_matched = len(growth_df)
    n_uncertain = 0
    if not growth_df.empty and "status" in growth_df.columns:
        n_uncertain = int((growth_df["status"] == "UNCERTAIN").sum())

    mean_growth = max_growth = "N/A"
    if not growth_df.empty and "depth_growth_pct_per_yr" in growth_df.columns:
        valid = growth_df["depth_growth_pct_per_yr"].dropna()
        if len(valid):
            mean_growth = f"{valid.mean():.3f}"
            max_growth = f"{valid.max():.3f}"

    # Generate charts
    chart_histogram = depth_growth_histogram(growth_df)
    chart_scatter = growth_scatter(growth_df)
    chart_remaining_life = remaining_life_histogram(growth_df)
    chart_worst = worst_n_chart(growth_df, n=20)
    chart_alignment = segment_alignment_plot(segments, residuals)

    # Summary table
    summary_table = ""
    if not summary_df.empty:
        summary_table = summary_df.to_html(index=False, classes="", float_format="%.4f")

    # Dig list table
    dig_list_table = ""
    if not growth_df.empty and "severity_score" in growth_df.columns:
        dig_cols = [
            "feature_id_a", "feature_type", "distance_a",
            "depth_pct_a", "depth_pct_b",
            "depth_growth_pct_per_yr", "remaining_life_yr",
            "projected_depth_pct", "severity_score", "status",
        ]
        available = [c for c in dig_cols if c in growth_df.columns]
        dig = growth_df[available].head(50)
        dig_list_table = dig.to_html(index=False, classes="", float_format="%.2f")

    # Render
    html = _HTML_TEMPLATE.render(
        run_a=run_id_a,
        run_b=run_id_b,
        years_between=years_between,
        n_matched=n_matched,
        n_uncertain=n_uncertain,
        n_missing=len(missing_df),
        n_new=len(new_df),
        mean_growth=mean_growth,
        max_growth=max_growth,
        chart_histogram=chart_histogram,
        chart_scatter=chart_scatter,
        chart_remaining_life=chart_remaining_life,
        chart_worst=chart_worst,
        chart_alignment=chart_alignment,
        summary_table=summary_table,
        dig_list_table=dig_list_table,
    )

    output_path = Path(output_path)
    output_path.write_text(html, encoding="utf-8")
    log.info("Wrote HTML report to %s", output_path)
    return output_path
